name: Daily News Mail

on:
  schedule:
    - cron: '0 22 * * *'  # 오전 7시
    - cron: '0 8 * * *'   # 오후 5시
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python news_mail.py
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
